export const homes = [
  {
    id: 1,
    image: "/images/house-1.jpeg",
    title: "Beautiful Family House",
    nation: "USA",
    rooms: "5 rooms",
    meter: "325 m",
    price: "$1,200,00",
  },
  {
    id: 2,
    image: "/images/house-2.jpeg",
    title: "Modren Glass Villa",
    nation: "Canda",
    rooms: "5 rooms",
    meter: "200 m",
    price: "$1,400,00",
  },
  {
    id: 3,
    image: "/images/house-3.jpeg",
    title: "Cazy Country House",
    nation: "UK",
    rooms: "6 rooms",
    meter: "600 m",
    price: "$3,600,00",
  },
  {
    id: 4,
    image: "/images/house-4.jpeg",
    title: "Large Rustical Villa",

    nation: "Portugal",
    rooms: "7 rooms",
    meter: "500 m",
    price: "$6,800,00",
  },
  {
    id: 5,
    image: "/images/house-5.jpeg",
    title: "Majestic Place House",
    nation: "Germany",
    rooms: "10 rooms",
    meter: "325 m",
    price: "$8,200,00",
  },
  {
    id: 6,
    image: "/images/house-6.jpeg",
    title: "Modrem Family Apartment",
    nation: "India",
    rooms: "15 rooms",
    meter: "500 m",
    price: "$9,200,00",
  },
];
